### ISSUE TITLE
"apply from" typo in README.md

### ISSUE THREAD

**Issue by wtfacoconut** [gocd/gocd-plugin-gradle-task-helpers#4]
Issue present in commit: 0e677dfa3c0cc2d2b620d26fd21fb3fa5e9cf114

The following example in the README.md file has a small typo:
`apply from: apply from: "https://raw.githubusercontent.com/gocd/gocd-plugin-gradle-task-helpers/master/helper.gradle?_=${(int) (new Date().toInstant().epochSecond / 60)}"`

It has `apply from:` twice in the same line at the beginning, which is incorrect.

**Comment by arvindsv** [comment]
@wtfacoconut Thank you. Fixed in: https://github.com/gocd/gocd-plugin-gradle-task-helpers/commit/339254c7d778705797cf71f0a3f67fe51e81c44d
